from criador_json import criador_json as cj
import valores_globais

# carrega valores das opcoes em "conf/dados_tipo.json" ou cria arquivo a partir deste json padrão.
json_inicial = (
    '{\n'
    '  "json_ver": 2,\n'
    '  "caminhos": {\n'
    '    "dosbox": "\\"C:\\\\win apps\\\\emu utils\\\\DOSBox-0.74-3 x86\\\\DOSBox.exe\\"",\n'
    '    "openmsx": "\\"d:\\\\video games\\\\emuladores\\\\msx\\\\openmsx\\\\AMD64\\\\openmsx.bat\\"",\n'
    '    "ootake": "\\"D:\\\\video games\\\\emuladores\\\\pcengine\\\\ootake\\\\Ootake301\\\\Ootake.exe\\"",\n'
    '    "meisei": "\\"d:\\\\video games\\\\emuladores\\\\msx\\\\meisei 1.3.2 x86\\\\meisei.exe\\"",\n'
    '    "fmsx": "\\"d:\\\\video games\\\\emuladores\\\\msx\\\\fmsx\\\\x86\\\\fMSX.exe\\"",\n'
    '    "no$msx": "\\"d:\\\\video games\\\\emuladores\\\\msx\\\\no$msx\\\\x86\\\\NO$MSX.EXE\\"",\n'
    '    "brmsx": "\\"d:\\\\video games\\\\emuladores\\\\msx\\\\brmsx\\\\dos\\"",\n'
    '    "dos2dsk": "\\"D:\\\\msx_arquivos\\\\boot\\\\dos2.dsk\\"",\n'
    '    "meka": "\\"D:\\\\video games\\\\emuladores\\\\master system\\\\mekaw-2023-08-26 win32\\\\mekaw.exe\\"",\n'
    '    "fusion": "\\"D:\\\\video games\\\\emuladores\\\\multiple systems\\\\fusion\\\\fusion 3.64 win32\\\\Fusion364\\\\Fusion.exe\\"",\n'
    '    "fceux": "\\"d:\\\\video games\\\\emuladores\\\\nes\\\\fceux-2.3.0-win32\\\\fceux.exe\\"",\n'
    '    "snes9x": "\\"d:\\\\video games\\\\emuladores\\\\super nes\\\\snes9x\\\\snes9x_1.60_x64\\\\snes9x-x64.exe\\"",\n'
    '    "no$2k6": "\\"D:\\\\video games\\\\emuladores\\\\atari 2600\\\\NO$2K6 win32\\\\NO$2K6.EXE\\"",\n'
    '    "yabasanshiro": "\\"D:\\\\video games\\\\emuladores\\\\saturn\\\\yabasanshiro\\\\yabasanshiro-1.16.7-153d01\\\\yabasanshiro.exe\\"",\n'
    '    "magicengine": "\\"D:\\\\video games\\\\emuladores\\\\pcengine\\\\magic engine\\\\Magic-Engine 1.1.3\\\\x86\\\\pce.exe\\"",\n'
    '    "turboengine": "\\"D:\\\\video games\\\\emuladores\\\\pcengine\\\\turboengine\\\\TurboEngine032\\\\TurboEngine.exe\\"",\n'
    '    "tgemu": "\\"D:\\\\video games\\\\emuladores\\\\pcengine\\\\tgemu\\"",\n'
    '    "otvdm": "\\"C:\\\\win apps\\\\emu utils\\\\otvdm-v0.9.0\\\\otvdmw.exe\\""\n'
    '  },\n'
    '  "help": {\n'
    '    "cmd": ["?a - alvo (apenas nome)", "?A - alvo (apena nome sem extensão)",\n'
    '      "?d - diretorio destino relativo", "?D - diretorio destino completo",\n'
    '      "?c - caminho completo com nome de arquivo", "?*substring_nome* - arquivo que possua o substring no nome",\n'
    '      "?t - caminho do diretorio temporario relativo", "?T - caminho do diretorio temporario completo",\n'
    '      "?u - drive temporário sem barra", "?U - drive temporário com barra"\n'
    '    ],\n'
    '    "ext": [],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch 00dosbox.bat DOSBOX autostart": {\n'
    '    "cmd": ["caminho:dosbox", "-fullscreen", "-c", "\\"mount ?u ?U\\"",\n'
    '      "-c", "?u", "-c", "\\"cd ?d\\"", "-c", "\\"00dosbox.bat\\""],\n'
    '    "ext": ["00dosbox.bat"],\n'
    '    "dos": true,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "launch 16bit DOS executable with DOSBOX": {\n'
    '    "cmd": ["caminho:dosbox", "-fullscreen", "-c", "\\"mount ?u ?U\\"",\n'
    '      "-c", "?u", "-c", "\\"cd ?d\\"", "-c", "\\"?a\\""],\n'
    '    "ext": [".bat", ".com", ".exe"],\n'
    '    "dos": true,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "launch brmsx msx2 (dosbox) with MSXDSK image": {\n'
    '    "cmd": ["caminho:dosbox", "-fullscreen", "-c", "mount", "?u", "?U",\n'
    '      "-c", "mount", "c:", "caminho:brmsx", "-c", "c:", "-c",\n'
    '      "\\"BRMSX -noenter -msx2 -mapper 4 -diska ?c\\"", "-c", "exit"],\n'
    '    "ext": [".dsk"],\n'
    '    "dos": true,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch brmsx (dosbox) with MSXDSK image": {\n'
    '    "cmd": ["caminho:dosbox", "-fullscreen", "-c", "mount", "?u", "?U",\n'
    '      "-c", "mount", "c:", "caminho:brmsx", "-c", "c:", "-c",\n'
    '      "\\"BRMSX -noenter -mapper 4 -diska ?c\\"", "-c", "exit"],\n'
    '    "ext": [".dsk"],\n'
    '    "dos": true,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "*launch openmsx with MSXDSK image as hdd": {\n'
    '    "cmd": ["caminho:openmsx", "-machine", "CIEL_Expert-Turbo", "-ext", "ide", "-hda"],\n'
    '    "ext": [".dsk"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "launch openmsx with MSXDSK image as fdc": {\n'
    '    "cmd": ["caminho:openmsx", "-machine", "CIEL_Expert-Turbo", "-ext", "DDX_3.0", "-diska"],\n'
    '    "ext": [".dsk"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "launch openmsx with MSXDSK image as drive b: on dos2": {\n'
    '    "cmd": ["caminho:openmsx", "-machine", "CIEL_Expert-Turbo", "-ext", "ide", "-hda",\n'
    '      "caminho:dos2dsk", "-ext", "DDX_3.0", "-diska"],\n'
    '    "ext": [".dsk"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "launch meisei with MSXDSK image": {\n'
    '    "cmd": ["caminho:meisei"],\n'
    '    "ext": [".dsk"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch fmsx with MSXDSK image": {\n'
    '    "cmd": ["caminho:fmsx", "-diska"],\n'
    '    "ext": [".dsk"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch no$msx with MSXDSK image": {\n'
    '    "cmd": ["caminho:no$msx"],\n'
    '    "ext": [".dsk"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "*launch openmsx ciel expert with MSXROM image": {\n'
    '    "cmd": ["caminho:openmsx", "-machine", "CIEL_Expert-Turbo", "-cart"],\n'
    '    "ext": [".rom", ".mx1", ".mx2"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch fmsx with MSXROM image": {\n'
    '    "cmd": ["caminho:fmsx"],\n'
    '    "ext": [".rom", ".mx1", ".mx2"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch no$msx with MSXROM image": {\n'
    '    "cmd": ["caminho:no$msx"],\n'
    '    "ext": [".rom", ".mx1", ".mx2"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch brmsx (dosbox) with MSXROM image": {\n'
    '    "cmd": ["caminho:dosbox", "-fullscreen", "-c", "mount", "?u", "?U",\n'
    '      "-c", "mount", "c:", "caminho:brmsx", "-c", "c:", "-c",\n'
    '      "\\"BRMSX -noenter -mapper 4 ?c\\"", "-c", "exit"],\n'
    '    "ext": [".rom"],\n'
    '    "dos": true,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch brmsx msx2 (dosbox) with MSXROM image": {\n'
    '    "cmd": ["caminho:dosbox", "-fullscreen", "-c", "mount", "?u", "?U",\n'
    '      "-c", "mount", "c:", "caminho:brmsx", "-c", "c:", "-c",\n'
    '      "\\"BRMSX -noenter -mapper 4 -msx2 ?c\\"", "-c", "exit"],\n'
    '    "ext": [".rom"],\n'
    '    "dos": true,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "*launch openmsx with MSXCAS image": {\n'
    '    "cmd": ["caminho:openmsx", "-machine", "Gradiente_Expert_XP-800", "-cassetteplayer"],\n'
    '    "ext": [".cas", ".wav"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch fmsx with MSXCAS image": {\n'
    '    "cmd": ["caminho:fmsx"],\n'
    '    "ext": [".cas", ".wav"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch meisei with MSXCAS image": {\n'
    '    "cmd": ["caminho:meisei"],\n'
    '    "ext": [".cas", ".wav"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch openmsx msx2 with MSXBAS autoload": {\n'
    '    "cmd": ["echo",\n'
    '      "after time 10 {type \\"run \\\\\\"?a\\\\\\"\\\\r\\"} > ?u\\\\om_init.tcl", "&",\n'
    '      "caminho:openmsx",\n'
    '      "-machine", "Boosted_MSX2_EN", "-diska", "?D",\n'
    '      "-command", "\\"set fullscreen on\\"", "-script", "?u\\\\om_init.tcl",\n'
    '      "&", "del ?u\\\\om_init.tcl"],\n'
    '    "ext": [".bas", ".ldr"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "*launch openmsx msx1 with MSXBAS autoload": {\n'
    '    "cmd": ["echo",\n'
    '      "after time 13 {type \\"\\\\r\\"; after time 1 {type \\"run \\\\\\"?a\\\\\\"\\\\r\\"}} > ?u\\\\om_init.tcl", "&",\n'
    '      "caminho:openmsx",\n'
    '      "-machine", "Gradiente_Expert_XP-800", "-ext", "DDX_3.0", "-diska", "?D",\n'
    '      "-command", "\\"set fullscreen on\\"", "-script", "?u\\\\om_init.tcl",\n'
    '      "&", "del ?u\\\\om_init.tcl"],\n'
    '    "ext": [".bas", ".ldr"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "launch openmsx with MSXBIN image basic autoload": {\n'
    '    "cmd": ["echo",\n'
    '      "after time 10 {type \\"bload \\\\\\"?a\\\\\\",r\\\\r\\"} > ?u\\\\om_init.tcl", "&",\n'
    '      "caminho:openmsx",\n'
    '      "-machine", "Boosted_MSX2_EN", "-diska", "?D",\n'
    '      "-command", "\\"set fullscreen on\\"", "-script", "?u\\\\om_init.tcl",\n'
    '      "&", "del ?u\\\\om_init.tcl"],\n'
    '    "ext": [],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "*launch openmsx msx1 with MSXBIN image basic autoload": {\n'
    '    "cmd": ["echo",\n'
    '      "after time 13 {type \\"\\\\r\\"; after time 1 {type \\"bload \\\\\\"?a\\\\\\",r\\\\r\\"}} > ?u\\\\om_init.tcl", "&",\n'
    '      "caminho:openmsx",\n'
    '      "-machine", "Gradiente_Expert_XP-800", "-ext", "DDX_3.0", "-diska", "?D",\n'
    '      "-command", "\\"set fullscreen on\\"", "-script", "?u\\\\om_init.tcl",\n'
    '      "&", "del ?u\\\\om_init.tcl"],\n'
    '    "ext": [],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "launch brmsx (dosbox) with MSXBAS image": {\n'
    '    "cmd": ["caminho:dosbox", "-fullscreen", "-c", "mount", "?u", "?U",\n'
    '      "-c", "mount", "c:", "caminho:brmsx", "-c", "c:", "-c",\n'
    '      "\\"BRMSX -noenter -mapper 4 -mount ?D\\"", "-c", "exit"],\n'
    '    "ext": [".bas", ".ldr"],\n'
    '    "dos": true,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "launch brmsx msx2 (dosbox) with MSXBAS image": {\n'
    '    "cmd": ["caminho:dosbox", "-fullscreen", "-c", "mount", "?u", "?U",\n'
    '      "-c", "mount", "c:", "caminho:brmsx", "-c", "c:", "-c",\n'
    '      "\\"BRMSX -noenter -msx2 -mapper 4 -mount ?D\\"", "-c", "exit"],\n'
    '    "ext": [".bas", ".ldr"],\n'
    '    "dos": true,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "*boot target MSXDOS with openmsx msx1 and auto dir *.com": {\n'
    '    "cmd": ["echo",\n'
    '      "after time 10 {type \\"dir *.com\\\\r\\"} > ?u\\\\om_init.tcl", "&",\n'
    '      "caminho:openmsx",\n'
    '      "-machine", "Gradiente_Expert_XP-800", "-ext", "ram512k", "-ext", "ide",\n'
    '      "-command", "\\"diskmanipulator create ?u\\\\hda.dsk 32M\\"",\n'
    '      "-command", "\\"hda ?u\\\\hda.dsk\\"",\n'
    '      "-command", "\\"diskmanipulator import hda ?D\\"",\n'
    '      "-command", "\\"set fullscreen on\\"", "-script", "?u\\\\om_init.tcl",\n'
    '      "&", "del ?u\\\\om_init.tcl", "&", "del ?u\\\\hda.dsk"],\n'
    '    "ext": ["msxdos.sys", "command.com", "msxdos2.sys", "command2.com"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "boot target MSXDOS with openmsx msx2 and auto dir *.com": {\n'
    '    "cmd": ["echo",\n'
    '      "after time 10 {type \\"dir *.com\\\\r\\"} > ?u\\\\om_init.tcl", "&",\n'
    '      "caminho:openmsx",\n'
    '      "-machine", "Boosted_MSX2_EN", "-ext", "ide",\n'
    '      "-command", "\\"diskmanipulator create ?u\\\\hda.dsk 32M\\"",\n'
    '      "-command", "\\"hda ?u\\\\hda.dsk\\"",\n'
    '      "-command", "\\"diskmanipulator import hda ?D\\"",\n'
    '      "-command", "\\"set fullscreen on\\"", "-script", "?u\\\\om_init.tcl",\n'
    '      "&", "del ?u\\\\om_init.tcl", "&", "del ?u\\\\hda.dsk"],\n'
    '    "ext": ["msxdos.sys", "command.com", "msxdos2.sys", "command2.com"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "*load MSX-DOS promgram / Z80-like code with openmsx msx1 on emulated hda MSXDOS2 autoload": {\n'
    '    "cmd": ["echo",\n'
    '      "after time 15 {type \\"?a\\\\r\\"} > ?u\\\\om_init.tcl", "&",\n'
    '      "caminho:openmsx",\n'
    '      "-machine", "Gradiente_Expert_XP-800", "-ext", "ram512k", "-ext ide",\n'
    '      "-command", "\\"diskmanipulator create ?u\\\\hda.dsk 32M\\"",\n'
    '      "-command", "\\"hda ?u\\\\hda.dsk\\"",\n'
    '      "-command", "\\"diskmanipulator import hda ?D\\"",\n'
    '      "-command", "\\"diskmanipulator import hda d:\\\\msx_arquivos\\\\boot\\\\dos2\\"",\n'
    '      "-command", "\\"set fullscreen on\\"", "-script ?u\\\\om_init.tcl",\n'
    '      "&", "del ?u\\\\om_init.tcl", "&", "del ?u\\\\hda.dsk"],\n'
    '    "ext": [".bat", ".com"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "load MSX-DOS promgram / Z80-like code with openmsx msx2 on emulated hda MSXDOS2 autoload": {\n'
    '    "cmd": ["echo",\n'
    '      "after time 20 {type \\"?a\\\\r\\"} > ?u\\\\om_init.tcl", "&",\n'
    '      "caminho:openmsx",\n'
    '      "-machine", "Boosted_MSX2+_JP", "-ext ide",\n'
    '      "-command", "\\"diskmanipulator create ?u\\\\hda.dsk 32M\\"",\n'
    '      "-command", "\\"hda ?u\\\\hda.dsk\\"",\n'
    '      "-command", "\\"diskmanipulator import hda ?D\\"",\n'
    '      "-command", "\\"diskmanipulator import hda d:\\\\msx_arquivos\\\\boot\\\\dos2\\"",\n'
    '      "-command", "\\"set fullscreen on\\"", "-script ?u\\\\om_init.tcl",\n'
    '      "&", "del ?u\\\\om_init.tcl", "&", "del ?u\\\\hda.dsk"],\n'
    '    "ext": [".bat", ".com"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "launch meka with Master System / Game Gear / SG1000 / SC3000 / Z80-like code / MSXROM image": {\n'
    '    "cmd": ["caminho:meka"],\n'
    '    "ext": [".sms", ".gg", ".sg", ".sc"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch fusion with Mega Drive / Sega 32x image": {\n'
    '    "cmd": ["caminho:fusion"],\n'
    '    "ext": [".smd", ".md", ".gen", ".32x"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch fusion with SEGA CD / MEGA CD / SEGA CD 32X image": {\n'
    '    "cmd": ["caminho:fusion", "\\"?D\\\\?*.cue*\\""],\n'
    '    "ext": [".iso", ".bin"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "launch fceux with NES image": {\n'
    '    "cmd": ["caminho:fceux"],\n'
    '    "ext": [".nes"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch snes9x with Super Nintendo image": {\n'
    '    "cmd": ["caminho:snes9x"],\n'
    '    "ext": [".sfc", ".smc"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch no$2k6 with Atari 2600 image": {\n'
    '    "cmd": ["caminho:no$2k6"],\n'
    '    "ext": [".a26"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch yabasanshiro with Saturn CHD image": {\n'
    '    "cmd": ["caminho:yabasanshiro", "-a", "-i", "\\"?c\\""],\n'
    '    "ext": [".chd"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "launch yabasanshiro with Saturn BIN / ISO image": {\n'
    '    "cmd": ["caminho:yabasanshiro", "-a", "-i", "\\"?D\\\\?*.cue*\\""],\n'
    '    "ext": [".iso", ".bin"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  },\n'
    '  "launch tgemu (dosbox) with PCengine / TurboGrax16 image": {\n'
    '    "cmd": ["caminho:dosbox", "-fullscreen", "-c", "mount", "?u", "?U",\n'
    '      "-c", "mount", "c:", "caminho:tgemu", "-c", "c:", "-c",\n'
    '      "\\"PCE ?c -scanlines on -sound on -fps -skip 1\\""],\n'
    '    "ext": [".pce"],\n'
    '    "dos": true,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch magicengine with PCengine / TurboGrax16 image": {\n'
    '    "cmd": ["caminho:magicengine"],\n'
    '    "ext": [".pce"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "*launch Ootake with PCengine / TurboGrax16 image": {\n'
    '    "cmd": ["caminho:ootake"],\n'
    '    "ext": [".pce"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch turboengine with PCengine / TurboGrax16 rom image": {\n'
    '    "cmd": ["caminho:turboengine"],\n'
    '    "ext": [".pce"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": false\n'
    '  },\n'
    '  "launch 16bit Windows exec with otvdm": {\n'
    '    "cmd": ["caminho:otvdm"],\n'
    '    "ext": [".exe", ".scr"],\n'
    '    "dos": false,\n'
    '    "extrai_tudo": true\n'
    '  }\n'
    '}'
)
cj.verbose = valores_globais.debug
dados_tipo = cj.carrega_ou_cria_config("conf/dados_tipo.json", json_inicial)
