from criador_json import criador_json as cj
import valores_globais

# carrega valores das opcoes em "conf/descompactadores.json" ou cria arquivo a partir deste json padrão.
json_inicial = (
    '{\n'
    '   "json_ver": 1,\n'
    '   ".7z": [\n'
    '      "extrair_arquivo_com_7zip",\n'
    '      "listar_conteudo_com_7z"\n'
    '   ],\n'
    '   ".rar": [\n'
    '      "extrair_arquivo_com_7zip",\n'
    '      "listar_conteudo_com_7z"\n'
    '   ],\n'
    '   ".zip": [\n'
    '      "extrair_arquivo_com_7zip",\n'
    '      "listar_conteudo_com_7z"\n'
    '   ],\n'
    '   ".bz2": [\n'
    '      "descompactar_bzip2",\n'
    '      "listar_conteudo_bzip2"\n'
    '   ],\n'
    '   ".gz": [\n'
    '      "descompactar_gzip",\n'
    '      "listar_conteudo_gzip"\n'
    '   ],\n'
    '   ".xz": [\n'
    '      "descompactar_xz",\n'
    '      "listar_conteudo_xz"\n'
    '   ],\n'
    '   ".tar": [\n'
    '      "descompactar_tar",\n'
    '      "listar_conteudo_tar"\n'
    '   ],\n'
    '   ".tar.bz2": [\n'
    '      "descompactar_tar_bz2",\n'
    '      "listar_conteudo_tar"\n'
    '   ],\n'
    '   ".tar.gz": [\n'
    '      "descompactar_tar_gz",\n'
    '      "listar_conteudo_tar"\n'
    '   ],\n'
    '   ".lzh": [\n'
    '      "extrair_arquivo_com_7zip",\n'
    '      "listar_conteudo_com_7z"\n'
    '   ],\n'
    '   ".tar.xz": [\n'
    '      "descompactar_tar_xz",\n'
    '      "listar_conteudo_tar"\n'
    '   ],\n'
    '   ".lha": [\n'
    '      "extrair_arquivo_com_7zip",\n'
    '      "listar_conteudo_com_7z"\n'
    '   ],\n'
    '   ".pma": [\n'
    '      "extrair_arquivo_com_7zip",\n'
    '      "listar_conteudo_com_7z"\n'
    '   ],\n'
    '   ".arj": [\n'
    '      "extrair_arquivo_com_7zip",\n'
    '      "listar_conteudo_com_7z"\n'
    '   ]\n'
    '}'
)
cj.verbose = valores_globais.debug
descompactadores = cj.carrega_ou_cria_config("conf/descompactadores.json", json_inicial)
